export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL"

export const LOCATE_USER_REQUEST = "LOCATE_USER_REQUEST"
export const LOCATE_USER_SUCCESS = "LOCATE_USER_SUCCESS"
export const LOCATE_USER_FAIL = "LOCATE_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"