export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_RESET = "NEW_POST_RESET";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const MYFEED_POSTS_REQUEST = "MYFEED_POST_REQUEST"
export const MYFEED_POSTS_SUCCESS = "MYFEED_POST_SUCCESS"
export const MYFEED_POSTS_RESET = "MYFEED_POST_RESET"
export const MYFEED_POSTS_FAIL = "MYFEED_POST_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
