// export const NEW_CHUM_REQUEST_REQUEST = "NEW_CHUM_REQUEST_REQUEST";
// export const NEW_CHUM_REQUEST_SUCCESS = "NEW_CHUM_REQUEST_SUCCESS";
// export const NEW_CHUM_REQUEST_RESET = "NEW_CHUM_REQUEST_RESET";
// export const NEW_CHUM_REQUEST_FAIL = "NEW_CHUM_REQUEST_FAIL";

export const FETCH_CHUMS_REQUEST = "FETCH_CHUMS_REQUEST"
export const FETCH_CHUMS_SUCCESS = "FETCH_CHUMS_SUCCESS"
export const FETCH_CHUMS_FAIL = "FETCH_CHUMS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"